# Generated by Django 4.0.3 on 2022-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=10)),
                ('quantidade_de_paginas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('capa', models.URLField()),
                ('editora', models.CharField(max_length=30)),
                ('edicao', models.DecimalField(decimal_places=0, max_digits=5)),
                ('categoria', models.CharField(max_length=30)),
                ('sinopse', models.TextField()),
                ('data_de_publicacao', models.DateField()),
            ],
        ),
    ]
